import { useNavigate } from 'react-router-dom';
import Button from "./Button.jsx"; 

export default function HeroBanner() {
  const navigate = useNavigate();

  // Swapped to min-h-[100svh] for true mobile fullscreen
  return (
    <section className="relative w-full min-h-[100svh] overflow-hidden bg-black">
      
      {/* 1. The Cinematic Montage Background (Combined Sports) */}
      <div className="absolute inset-0 w-full h-full overflow-hidden">
        {/* Hero Video Loop */}
        <video 
          className="w-full h-full object-cover opacity-90"
          autoPlay 
          loop 
          muted 
          playsInline
          poster="/images/hero-fallback.jpg"
        >
          {/* Replace this src with the video generated by Gemini */}
          <source src="/images/hero-video.mp4" type="video/mp4" />
        </video>
      </div>

      {/* 2. The Gradient Overlay */}
      <div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-black/40"></div>

      {/* 3. The Content Container */}
      <div className="absolute inset-0 flex flex-col justify-center px-6 z-10">
        <div className="max-w-7xl mx-auto w-full">
          
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-1000">
            <span className="inline-block bg-[#c8102e] text-white font-bold uppercase tracking-widest text-xs px-3 py-1 rounded-full mb-4 shadow-lg">
              Velkomin á Ásvelli
            </span>
            
            <h1 className="text-5xl md:text-7xl lg:text-8xl font-black italic tracking-tighter text-white leading-none drop-shadow-xl mb-6 max-w-4xl pr-4">
              HJARTAÐ SLÆR <br /> 
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#c8102e] to-red-400 pr-3">
                Í HAFNARFIRÐI
              </span>
            </h1>
            
            <p className="text-lg md:text-xl text-gray-200 font-body max-w-2xl mb-8 drop-shadow-md">
              Eitt stærsta og sigursælasta íþróttafélag landsins. Við byggjum á stolti, liðsheild og óbilandi baráttuanda.
            </p>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-4">
              
              <Button 
                variant="primary" 
                icon="arrow_downward" 
                iconPosition="right"
                onClick={() => {
                  const newsSection = document.getElementById('news');
                  if (newsSection) {
                    newsSection.scrollIntoView({ behavior: 'smooth' });
                  }
                }}
              >
                Nýjustu fréttir
              </Button>

              <Button 
                variant="overlay" 
                icon="live_tv" 
                iconPosition="right"
                onClick={() => navigate('/leikvakt')}
              >
                Fara á Leikjavaktina
              </Button>

            </div>
          </div>

        </div>
      </div>
      
    </section>
  );
}